---
# Worker Group-Specific Declarative Resource Management
#
# This example demonstrates the new worker_group parameter available
# in all declarative modules across the Cribl Ansible collections.
#
# Key Benefits:
# - Same module name for global and worker group-specific resources
# - Consistent API across all resource types
# - Backward compatible - existing playbooks work unchanged
# - Allows different configurations per worker group

- name: Worker Group-Specific Resource Management Demo
  hosts: localhost
  gather_facts: false
  vars:
    cribl_url: "{{ lookup('env', 'CRIBL_URL') | default('https://cribl.example.com', true) }}"
    cribl_username: "{{ lookup('env', 'CRIBL_USERNAME') | default('admin', true) }}"
    cribl_password: "{{ lookup('env', 'CRIBL_PASSWORD') }}"

  tasks:
    # ============================================================================
    # AUTHENTICATION
    # ============================================================================
    
    - name: Authenticate with Cribl
      cribl.core.auth_session:
        base_url: "{{ cribl_url }}"
        username: "{{ cribl_username }}"
        password: "{{ cribl_password }}"
        validate_certs: false
      register: cribl_session
      no_log: true

    # OR use OAuth2 authentication for Cribl Cloud
    - name: Authenticate with Cribl Cloud
      cribl.core.auth_session:
        base_url: https://main-myorg.cribl.cloud
        client_id: "{{ cribl_client_id }}"
        client_secret: "{{ cribl_client_secret }}"
        validate_certs: true
      register: session
      no_log: true

    # ============================================================================
    # SCENARIO 1: Environment-Specific Pipelines
    # ============================================================================
    
    - name: Create data masking pipeline for production
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: data_masking
        worker_group: production # Leave blank for standalone
        conf:
          description: Aggressive data masking for production
          functions:
            - id: mask
              filter: "true"
              conf:
                rules:
                  - matchRegex: /\b\d{3}-\d{2}-\d{4}\b/g
                    replaceExpr: "'XXX-XX-XXXX'"
                  - matchRegex: /\b\d{16}\b/g
                    replaceExpr: "'XXXXXXXXXXXX' + value.slice(-4)"
        state: present

    - name: Create data masking pipeline for development
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: data_masking
        worker_group: development
        conf:
          description: Minimal masking for development environment
          functions:
            - id: mask
              filter: "true"
              conf:
                rules:
                  - matchRegex: /\b\d{3}-\d{2}-\d{4}\b/g
                    replaceExpr: "'XXX-XX-' + value.slice(-4)"
        state: present

    # ============================================================================
    # SCENARIO 2: Geographic Distribution
    # ============================================================================

    - name: Configure Splunk output for US East region
      cribl.stream.output:
        session: "{{ cribl_session.session }}"
        id: splunk_primary
        worker_group: us-east-workers
        state: present
        conf:
          type: syslog
          disabled: false
          sendToRoutes: true
          pqEnabled: false
          streamtags: []
          host: 0.0.0.0
          maxBufferSize: 1000
          ipWhitelistRegex: /.*/
          timestampTimezone: local
          singleMsgUdpPackets: false
          enableProxyHeader: false
          keepFieldsList: []
          octetCounting: false
          inferFraming: true
          strictlyInferOctetCounting: true
          allowNonStandardAppName: false
          maxActiveCxn: 1000
          socketIdleTimeout: 0
          socketEndingMaxWait: 30
          socketMaxLifespan: 0
          tls:
            disabled: true
          enableLoadBalancing: false
          tcpPort: 20151

    - name: Configure S3 output
      cribl.stream.output:
        session: "{{ cribl_session.session }}"
        id: splunk_primary
        worker_group: eu-west-workers
        conf:
          type: s3
          bucket: testbucket-123123
          systemFields:
            - cribl_pipe
          streamtags: []
          awsAuthenticationMethod: auto
          signatureVersion: v4
          reuseConnections: true
          rejectUnauthorized: true
          enableAssumeRole: false
          durationSeconds: 3600
          stagePath: $CRIBL_HOME/state/outputs/staging
          addIdToStagePath: true
          destPath: ""
          objectACL: private
          removeEmptyDirs: true
          partitionExpr: "C.Time.strftime(_time ? _time : Date.now()/1000, '%Y/%m/%d')"
          format: json
          baseFileName: '`CriblOut`'
          fileNameSuffix: '`.${C.env["CRIBL_WORKER_ID"]}.${__format}${__compression === "gzip" ? ".gz" : ""}`'
          maxFileSizeMB: 32
          maxOpenFiles: 100
          headerLine: ""
          writeHighWaterMark: 64
          onBackpressure: block
          deadletterEnabled: false
          onDiskFullBackpressure: block
          forceCloseOnShutdown: false
          maxFileOpenTimeSec: 300
          maxFileIdleTimeSec: 30
          maxConcurrentFileParts: 4
          verifyPermissions: true
          maxClosingFilesToBackpressure: 100
          compress: gzip
          compressionLevel: best_speed
          emptyDirCleanupSec: 300
          directoryBatchSize: 1000

    # ============================================================================
    # SCENARIO 3: Testing and Validation
    # ============================================================================

    - name: Deploy new pipeline to canary worker group first
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: new_feature_v2
        worker_group: canary
        conf:
          description: New feature being tested in canary
          functions:
            - id: eval
              conf:
                add:
                  - name: version
                    value: "'v2'"
        state: present

    - name: After validation, deploy to production
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: new_feature_v2
        worker_group: production
        conf:
          description: New feature validated and deployed to production
          functions:
            - id: eval
              conf:
                add:
                  - name: version
                    value: "'v2'"
        state: present

    

    # ============================================================================
    # SCENARIO 4: Cleanup and Maintenance
    # ============================================================================

    - name: Remove deprecated pipeline from specific worker group
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: old_pipeline_v1
        worker_group: production
        state: absent

    - name: Keep the same pipeline in other worker groups for backward compatibility
      cribl.stream.pipeline:
        session: "{{ cribl_session.session }}"
        id: old_pipeline_v1
        worker_group: legacy-systems
        state: present
